# Generated by Django 5.1 on 2024-08-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0002_improvement_rename_referral_user_referred_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='user',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
