# Generated by Django 5.1 on 2024-08-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0003_remove_user_referred_by_user_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_id',
            field=models.BigIntegerField(blank=True, max_length=255, null=True),
        ),
    ]
