# Generated by Django 5.1 on 2024-08-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0004_alter_user_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
        migrations.AddField(
            model_name='character',
            name='improvements',
            field=models.ManyToManyField(blank=True, to='telegram_miniapp.improvement'),
        ),
        migrations.AddField(
            model_name='user',
            name='character_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
