# Generated by Django 5.1 on 2024-08-30 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0006_alter_character_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_progress_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
