# Generated by Django 5.1 on 2024-09-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0008_user_last_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_collected',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
