# Generated by Django 5.1 on 2024-09-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0009_alter_user_last_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='character_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
