# Generated by Django 5.1 on 2024-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0010_alter_user_character_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
