# Generated by Django 5.1 on 2024-09-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0014_alter_user_points_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_per_hour', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='booster_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
