# Generated by Django 5.1 on 2024-09-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0015_booster_user_booster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
