# Generated by Django 5.1 on 2024-09-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0016_remove_wallet_user_wallet_is_connected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('creator_id', models.BigIntegerField(null=True)),
                ('count_members', models.BigIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='club_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
