# Generated by Django 5.1 on 2024-10-08 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0017_club_user_club_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_miniapp.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='telegram_miniapp.user')),
            ],
        ),
    ]
