# Generated by Django 5.1 on 2024-10-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_miniapp', '0018_remove_task_description_remove_task_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_miniapp.booster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosters', to='telegram_miniapp.user')),
            ],
        ),
    ]
